version: "3.9"
services:
  postgres:
    container_name: metric_db
    image: postgres
    restart: unless-stopped
    volumes:
      - /Users/mac/psql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "metric"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin1234"
    ports:
      - "5432:5432"